version: 0.0
os: linux

files:
  - source: /target/SpringChat-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: Start_Server.sh
      timeout: 300
      runas: ec2-user